---
title: "jsonStrings"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE)
```

```{r package}
library(jsonStrings)
options("jsonStrings.prettyPrint" = TRUE) # for pretty-printing the JSON strings
```


## Define a JSON string

```{r jsonstring}
jsonstring <- jsonString("
  {
    \"foo\": \"hello\",
    \"bar\": {\"x\": 1, \"y\": 2},
    \"baz\": [9, 99, null]
  }
")
```

## Extract a JSON value

```{r}
jsonAt(jsonstring, "foo")
jsonAt(jsonstring, c("bar", "y"))
jsonAt(jsonstring, list("baz", 2))
```

## Erase a JSON value

```{r}
jsonErase(jsonstring, "baz")
```

## Check existence of a property

```{r}
jsonHasKey(jsonstring, "bar")
```

## Check a type

```{r}
jsonIs(jsonstring, "object")
```

## Add a property

```{r}
jsonAddProperty(jsonstring, "new", "[4,5]")
```

## Update a JSON string

```{r}
jsonUpdate(
  jsonstring,
  "{
    \"foo\": \"goodbye\",
    \"qux\": 10000
  }"
)
```

## Patch a JSON string

```{r}
jsonpatch <- jsonString("[
  {\"op\": \"remove\", \"path\": \"/foo\"},
  {\"op\": \"replace\", \"path\": \"/baz/2\", \"value\": 9999}
]")
jsonPatch(jsonstring, jsonpatch)
```



