# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_jsonHasKey <- function(jsonString, key) {
    .Call(`_jsonStrings_cpp_jsonHasKey`, jsonString, key)
}

cpp_jsonAt <- function(jsonString, keys, indices, isIndex) {
    .Call(`_jsonStrings_cpp_jsonAt`, jsonString, keys, indices, isIndex)
}

