# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name JsonString
#' @title Class of JSON strings objects
#' @description Type the name of the class to see its methods
#' @field new Constructor
#' @field mult Multiply by another Double object \itemize{
#' \item Parameter: other - The other Double object
#' \item Returns: product of the values
#' }
NULL

