# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

toJSONXptr <- function(string) {
    .Call(`_jsonStrings_toJSONXptr`, string)
}

read_json <- function(filename) {
    .Call(`_jsonStrings_read_json`, filename)
}

